contact_email: 'syeinfo@eienigeria.org'
mapit_url: 'http://nigeria.mapit.mysociety.org'
twitter_user: 'NGShineYourEye'
mapit_settings:
  baseurl: '/place/'
  area_types:
    - FED
    - SEN
    - STA
  data_directory: 'mapit'
